export const LANGUAGES = [
  { code: "uz", name: "O'zbek", flag: "🇺🇿" },
  { code: "ru", name: "Русский", flag: "🇷🇺" },
  { code: "en", name: "English", flag: "🇬🇧" },
  { code: "tr", name: "Türkçe", flag: "🇹🇷" },
  { code: "ar", name: "العربية", flag: "🇸🇦" },
  { code: "zh", name: "中文", flag: "🇨🇳" },
  { code: "ko", name: "한국어", flag: "🇰🇷" },
  { code: "ja", name: "日本語", flag: "🇯🇵" },
  { code: "de", name: "Deutsch", flag: "🇩🇪" },
  { code: "fr", name: "Français", flag: "🇫🇷" },
  { code: "es", name: "Español", flag: "🇪🇸" },
  { code: "hi", name: "हिन्दी", flag: "🇮🇳" },
  { code: "tg", name: "Тоҷикӣ", flag: "🇹🇯" },
  { code: "kk", name: "Қазақ", flag: "🇰🇿" },
  { code: "ky", name: "Кыргыз", flag: "🇰🇬" },
] as const;

export type LanguageCode = (typeof LANGUAGES)[number]["code"];

export function getLanguage(code: string) {
  return LANGUAGES.find((l) => l.code === code) ?? LANGUAGES[0];
}

export function getLanguageName(code: string) {
  return getLanguage(code).name;
}

// Web Speech API locale mapping
export const SPEECH_LOCALES: Record<string, string> = {
  uz: "uz-UZ",
  ru: "ru-RU",
  en: "en-US",
  tr: "tr-TR",
  ar: "ar-SA",
  zh: "zh-CN",
  ko: "ko-KR",
  ja: "ja-JP",
  de: "de-DE",
  fr: "fr-FR",
  es: "es-ES",
  hi: "hi-IN",
  tg: "tg-TJ",
  kk: "kk-KZ",
  ky: "ky-KG",
};

export const UI_TEXT = {
  uz: {
    appName: "Tcall",
    tagline: "Dunyo bilan til chegarasisiz gaplashing",
    login: "Kirish",
    register: "Ro'yxatdan o'tish",
    email: "Email",
    password: "Parol",
    name: "Ismingiz",
    language: "Sizning tilingiz",
    startCall: "Qo'ng'iroq boshlash",
    joinCall: "Qo'ng'iroqqa qo'shilish",
    roomId: "Xona kodi",
    dashboard: "Boshqaruv paneli",
    logout: "Chiqish",
    waiting: "Sherik kutilmoqda...",
    connected: "Ulandi",
    endCall: "Qo'ng'iroqni tugatish",
    mute: "Ovozni o'chirish",
    unmute: "Ovozni yoqish",
    videoOff: "Kamerani o'chirish",
    videoOn: "Kamerani yoqish",
    translation: "Real-time tarjima",
    copyLink: "Havolani nusxalash",
    copied: "Nusxalandi!",
    createRoom: "Yangi xona yaratish",
    recentCalls: "So'nggi qo'ng'iroqlar",
    noCalls: "Hali qo'ng'iroqlar yo'q",
    speaking: "gapirmoqda",
    translated: "tarjima",
    yourLanguage: "Sizning tilingiz",
    partnerLanguage: "Sherik tili",
    connecting: "Ulanmoqda...",
    ended: "Tugadi",
    shareLink: "Havolani sherigingizga yuboring",
    callEnded: "Qo'ng'iroq tugadi",
    callEndedDesc: "Sherik chiqib ketdi yoki qo'ng'iroq yakunlandi",
    backToDashboard: "Boshqaruv paneliga qaytish",
    mediaDenied: "Kamera yoki mikrofon ruxsati kerak",
    mediaDeniedDesc: "Brauzer sozlamalaridan kamera va mikrofonni yoqing",
    roomFull: "Xona to'liq",
    roomFullDesc: "Bu xonada allaqachon 2 kishi bor",
    roomError: "Ulanish xatosi",
    browserUnsupported: "Tarjima uchun Chrome yoki Edge kerak",
    browserUnsupportedDesc: "Nutqni tanish faqat Chrome/Edge brauzerlarida ishlaydi",
    voiceOn: "Ovozli tarjima yoqish",
    voiceOff: "Ovozli tarjima o'chirish",
    aiPowered: "OpenAI Whisper + GPT + TTS",
    joinError: "Xona topilmadi yoki to'liq",
    createRoomDesc: "Yangi video qo'ng'iroq xonasi yarating va havolani sherigingizga yuboring",
    joinRoomDesc: "Xona kodini kiriting yoki havoladan o'ting",
    translationInfo: "Qo'ng'iroq paytida sherigingiz boshqa tilde gapirsa, AI avtomatik tarjima qilib subtitr ko'rsatadi.",
  },
  ru: {
    appName: "Tcall",
    tagline: "Общайтесь с миром без языковых барьеров",
    login: "Вход",
    register: "Регистрация",
    email: "Email",
    password: "Пароль",
    name: "Ваше имя",
    language: "Ваш язык",
    startCall: "Начать звонок",
    joinCall: "Присоединиться",
    roomId: "Код комнаты",
    dashboard: "Панель управления",
    logout: "Выход",
    waiting: "Ожидание собеседника...",
    connected: "Подключено",
    endCall: "Завершить звонок",
    mute: "Выключить микрофон",
    unmute: "Включить микрофон",
    videoOff: "Выключить камеру",
    videoOn: "Включить камеру",
    translation: "Перевод в реальном времени",
    copyLink: "Копировать ссылку",
    copied: "Скопировано!",
    createRoom: "Создать комнату",
    recentCalls: "Недавние звонки",
    noCalls: "Звонков пока нет",
    speaking: "говорит",
    translated: "перевод",
    yourLanguage: "Ваш язык",
    partnerLanguage: "Язык собеседника",
    connecting: "Подключение...",
    ended: "Завершено",
    shareLink: "Отправьте ссылку собеседнику",
    callEnded: "Звонок завершён",
    callEndedDesc: "Собеседник вышел или звонок завершён",
    backToDashboard: "Вернуться в панель",
    mediaDenied: "Нужен доступ к камере и микрофону",
    mediaDeniedDesc: "Разрешите камеру и микрофон в настройках браузера",
    roomFull: "Комната заполнена",
    roomFullDesc: "В этой комнате уже 2 человека",
    roomError: "Ошибка подключения",
    browserUnsupported: "Для перевода нужен Chrome или Edge",
    browserUnsupportedDesc: "Распознавание речи работает только в Chrome/Edge",
    voiceOn: "Включить голосовой перевод",
    voiceOff: "Выключить голосовой перевод",
    aiPowered: "OpenAI Whisper + GPT + TTS",
    joinError: "Комната не найдена или заполнена",
    createRoomDesc: "Создайте комнату и отправьте ссылку собеседнику",
    joinRoomDesc: "Введите код комнаты или перейдите по ссылке",
    translationInfo: "Во время звонка AI автоматически переводит речь собеседника на ваш язык.",
  },
  en: {
    appName: "Tcall",
    tagline: "Talk to the world without language barriers",
    login: "Login",
    register: "Register",
    email: "Email",
    password: "Password",
    name: "Your name",
    language: "Your language",
    startCall: "Start Call",
    joinCall: "Join Call",
    roomId: "Room code",
    dashboard: "Dashboard",
    logout: "Logout",
    waiting: "Waiting for partner...",
    connected: "Connected",
    endCall: "End Call",
    mute: "Mute",
    unmute: "Unmute",
    videoOff: "Turn off camera",
    videoOn: "Turn on camera",
    translation: "Real-time translation",
    copyLink: "Copy link",
    copied: "Copied!",
    createRoom: "Create room",
    recentCalls: "Recent calls",
    noCalls: "No calls yet",
    speaking: "speaking",
    translated: "translation",
    yourLanguage: "Your language",
    partnerLanguage: "Partner language",
    connecting: "Connecting...",
    ended: "Ended",
    shareLink: "Share the link with your partner",
    callEnded: "Call ended",
    callEndedDesc: "Your partner left or the call has ended",
    backToDashboard: "Back to dashboard",
    mediaDenied: "Camera and microphone access required",
    mediaDeniedDesc: "Please allow camera and microphone in browser settings",
    roomFull: "Room is full",
    roomFullDesc: "This room already has 2 participants",
    roomError: "Connection error",
    browserUnsupported: "Chrome or Edge required for translation",
    browserUnsupportedDesc: "Speech recognition only works in Chrome/Edge browsers",
    voiceOn: "Enable voice translation",
    voiceOff: "Disable voice translation",
    aiPowered: "OpenAI Whisper + GPT + TTS",
    joinError: "Room not found or full",
    createRoomDesc: "Create a video call room and share the link with your partner",
    joinRoomDesc: "Enter room code or use the invitation link",
    translationInfo: "During the call, AI automatically translates your partner's speech to your language.",
  },
} as const;

export type UILocale = keyof typeof UI_TEXT;

export function getUI(lang: string): (typeof UI_TEXT)[UILocale] {
  if (lang in UI_TEXT) return UI_TEXT[lang as UILocale];
  return UI_TEXT.en;
}
