/** Qo'llab-quvvatlanadigan barcha tillar (65+) */
export const LANGUAGES = [
  { code: "uz", name: "O'zbek", flag: "🇺🇿" },
  { code: "ru", name: "Русский", flag: "🇷🇺" },
  { code: "en", name: "English", flag: "🇬🇧" },
  { code: "tr", name: "Türkçe", flag: "🇹🇷" },
  { code: "ar", name: "العربية", flag: "🇸🇦" },
  { code: "zh", name: "中文", flag: "🇨🇳" },
  { code: "ko", name: "한국어", flag: "🇰🇷" },
  { code: "ja", name: "日本語", flag: "🇯🇵" },
  { code: "de", name: "Deutsch", flag: "🇩🇪" },
  { code: "fr", name: "Français", flag: "🇫🇷" },
  { code: "es", name: "Español", flag: "🇪🇸" },
  { code: "hi", name: "हिन्दी", flag: "🇮🇳" },
  { code: "tg", name: "Тоҷикӣ", flag: "🇹🇯" },
  { code: "kk", name: "Қазақ", flag: "🇰🇿" },
  { code: "ky", name: "Кыргыз", flag: "🇰🇬" },
  { code: "pt", name: "Português", flag: "🇵🇹" },
  { code: "it", name: "Italiano", flag: "🇮🇹" },
  { code: "pl", name: "Polski", flag: "🇵🇱" },
  { code: "uk", name: "Українська", flag: "🇺🇦" },
  { code: "fa", name: "فارسی", flag: "🇮🇷" },
  { code: "ur", name: "اردو", flag: "🇵🇰" },
  { code: "bn", name: "বাংলা", flag: "🇧🇩" },
  { code: "pa", name: "ਪੰਜਾਬੀ", flag: "🇮🇳" },
  { code: "ta", name: "தமிழ்", flag: "🇮🇳" },
  { code: "te", name: "తెలుగు", flag: "🇮🇳" },
  { code: "mr", name: "मराठी", flag: "🇮🇳" },
  { code: "gu", name: "ગુજરાતી", flag: "🇮🇳" },
  { code: "ml", name: "മലയാളം", flag: "🇮🇳" },
  { code: "id", name: "Bahasa Indonesia", flag: "🇮🇩" },
  { code: "ms", name: "Bahasa Melayu", flag: "🇲🇾" },
  { code: "vi", name: "Tiếng Việt", flag: "🇻🇳" },
  { code: "th", name: "ไทย", flag: "🇹🇭" },
  { code: "my", name: "မြန်မာ", flag: "🇲🇲" },
  { code: "km", name: "ខ្មែរ", flag: "🇰🇭" },
  { code: "lo", name: "ລາວ", flag: "🇱🇦" },
  { code: "ne", name: "नेपाली", flag: "🇳🇵" },
  { code: "si", name: "සිංහල", flag: "🇱🇰" },
  { code: "mn", name: "Монгол", flag: "🇲🇳" },
  { code: "az", name: "Azərbaycan", flag: "🇦🇿" },
  { code: "ka", name: "ქართული", flag: "🇬🇪" },
  { code: "hy", name: "Հայերեն", flag: "🇦🇲" },
  { code: "he", name: "עברית", flag: "🇮🇱" },
  { code: "nl", name: "Nederlands", flag: "🇳🇱" },
  { code: "sv", name: "Svenska", flag: "🇸🇪" },
  { code: "no", name: "Norsk", flag: "🇳🇴" },
  { code: "da", name: "Dansk", flag: "🇩🇰" },
  { code: "fi", name: "Suomi", flag: "🇫🇮" },
  { code: "cs", name: "Čeština", flag: "🇨🇿" },
  { code: "sk", name: "Slovenčina", flag: "🇸🇰" },
  { code: "hu", name: "Magyar", flag: "🇭🇺" },
  { code: "ro", name: "Română", flag: "🇷🇴" },
  { code: "bg", name: "Български", flag: "🇧🇬" },
  { code: "hr", name: "Hrvatski", flag: "🇭🇷" },
  { code: "sr", name: "Српски", flag: "🇷🇸" },
  { code: "sl", name: "Slovenščina", flag: "🇸🇮" },
  { code: "lt", name: "Lietuvių", flag: "🇱🇹" },
  { code: "lv", name: "Latviešu", flag: "🇱🇻" },
  { code: "et", name: "Eesti", flag: "🇪🇪" },
  { code: "sq", name: "Shqip", flag: "🇦🇱" },
  { code: "mk", name: "Македонски", flag: "🇲🇰" },
  { code: "bs", name: "Bosanski", flag: "🇧🇦" },
  { code: "ps", name: "پښتو", flag: "🇦🇫" },
  { code: "sw", name: "Kiswahili", flag: "🇰🇪" },
  { code: "am", name: "አማርኛ", flag: "🇪🇹" },
  { code: "yo", name: "Yorùbá", flag: "🇳🇬" },
  { code: "ha", name: "Hausa", flag: "🇳🇬" },
  { code: "af", name: "Afrikaans", flag: "🇿🇦" },
  { code: "tl", name: "Filipino", flag: "🇵🇭" },
  { code: "be", name: "Беларуская", flag: "🇧🇾" },
  { code: "ca", name: "Català", flag: "🇪🇸" },
  { code: "eu", name: "Euskara", flag: "🇪🇸" },
  { code: "gl", name: "Galego", flag: "🇪🇸" },
  { code: "is", name: "Íslenska", flag: "🇮🇸" },
  { code: "ga", name: "Gaeilge", flag: "🇮🇪" },
  { code: "cy", name: "Cymraeg", flag: "🇬🇧" },
  { code: "mt", name: "Malti", flag: "🇲🇹" },
  { code: "lb", name: "Lëtzebuergesch", flag: "🇱🇺" },
] as const;

export type LanguageCode = (typeof LANGUAGES)[number]["code"];

/** Right-to-left languages (Arabic, Hebrew, Persian, Urdu, Pashto). */
export const RTL_LANGUAGES: ReadonlySet<string> = new Set(["ar", "he", "fa", "ur", "ps"]);

export function isRTL(code: string | null | undefined): boolean {
  if (!code) return false;
  return RTL_LANGUAGES.has(code.split("-")[0].toLowerCase());
}

export const SPEECH_LOCALES: Record<string, string> = {
  uz: "uz-UZ", ru: "ru-RU", en: "en-US", tr: "tr-TR", ar: "ar-SA",
  zh: "zh-CN", ko: "ko-KR", ja: "ja-JP", de: "de-DE", fr: "fr-FR",
  es: "es-ES", hi: "hi-IN", tg: "tg-TJ", kk: "kk-KZ", ky: "ky-KG",
  pt: "pt-PT", it: "it-IT", pl: "pl-PL", uk: "uk-UA", fa: "fa-IR",
  ur: "ur-PK", bn: "bn-BD", pa: "pa-IN", ta: "ta-IN", te: "te-IN",
  mr: "mr-IN", gu: "gu-IN", ml: "ml-IN", id: "id-ID", ms: "ms-MY",
  vi: "vi-VN", th: "th-TH", my: "my-MM", km: "km-KH", lo: "lo-LA",
  ne: "ne-NP", si: "si-LK", mn: "mn-MN", az: "az-AZ", ka: "ka-GE",
  hy: "hy-AM", he: "he-IL", nl: "nl-NL", sv: "sv-SE", no: "nb-NO",
  da: "da-DK", fi: "fi-FI", cs: "cs-CZ", sk: "sk-SK", hu: "hu-HU",
  ro: "ro-RO", bg: "bg-BG", hr: "hr-HR", sr: "sr-RS", sl: "sl-SI",
  lt: "lt-LT", lv: "lv-LV", et: "et-EE", sq: "sq-AL", mk: "mk-MK",
  bs: "bs-BA", ps: "ps-AF", sw: "sw-KE", am: "am-ET", yo: "yo-NG",
  ha: "ha-NG", af: "af-ZA", tl: "fil-PH", be: "be-BY", ca: "ca-ES",
  eu: "eu-ES", gl: "gl-ES", is: "is-IS", ga: "ga-IE", cy: "cy-GB",
  mt: "mt-MT", lb: "lb-LU",
};
