export const LANGUAGES = [
  { code: "uz", name: "O'zbek", flag: "🇺🇿" },
  { code: "ru", name: "Русский", flag: "🇷🇺" },
  { code: "en", name: "English", flag: "🇬🇧" },
  { code: "tr", name: "Türkçe", flag: "🇹🇷" },
  { code: "ar", name: "العربية", flag: "🇸🇦" },
  { code: "zh", name: "中文", flag: "🇨🇳" },
  { code: "ko", name: "한국어", flag: "🇰🇷" },
  { code: "ja", name: "日本語", flag: "🇯🇵" },
  { code: "de", name: "Deutsch", flag: "🇩🇪" },
  { code: "fr", name: "Français", flag: "🇫🇷" },
  { code: "es", name: "Español", flag: "🇪🇸" },
  { code: "hi", name: "हिन्दी", flag: "🇮🇳" },
  { code: "tg", name: "Тоҷикӣ", flag: "🇹🇯" },
  { code: "kk", name: "Қазақ", flag: "🇰🇿" },
  { code: "ky", name: "Кыргыз", flag: "🇰🇬" },
] as const;

export type LanguageCode = (typeof LANGUAGES)[number]["code"];

export function getLanguage(code: string) {
  return LANGUAGES.find((l) => l.code === code) ?? LANGUAGES[0];
}

export function getLanguageName(code: string) {
  return getLanguage(code).name;
}

// Web Speech API locale mapping
export const SPEECH_LOCALES: Record<string, string> = {
  uz: "uz-UZ",
  ru: "ru-RU",
  en: "en-US",
  tr: "tr-TR",
  ar: "ar-SA",
  zh: "zh-CN",
  ko: "ko-KR",
  ja: "ja-JP",
  de: "de-DE",
  fr: "fr-FR",
  es: "es-ES",
  hi: "hi-IN",
  tg: "tg-TJ",
  kk: "kk-KZ",
  ky: "ky-KG",
};

export const UI_TEXT = {
  uz: {
    appName: "Tcall",
    tagline: "Dunyo bilan til chegarasisiz gaplashing",
    login: "Kirish",
    register: "Ro'yxatdan o'tish",
    email: "Email",
    password: "Parol",
    name: "Ismingiz",
    language: "Sizning tilingiz",
    startCall: "Qo'ng'iroq boshlash",
    joinCall: "Qo'ng'iroqqa qo'shilish",
    roomId: "Xona kodi",
    dashboard: "Boshqaruv paneli",
    logout: "Chiqish",
    waiting: "Sherik kutilmoqda...",
    connected: "Ulandi",
    endCall: "Qo'ng'iroqni tugatish",
    mute: "Ovozni o'chirish",
    unmute: "Ovozni yoqish",
    videoOff: "Kamerani o'chirish",
    videoOn: "Kamerani yoqish",
    translation: "Real-time tarjima",
    copyLink: "Havolani nusxalash",
    copied: "Nusxalandi!",
    createRoom: "Yangi xona yaratish",
    recentCalls: "So'nggi qo'ng'iroqlar",
    noCalls: "Hali qo'ng'iroqlar yo'q",
    speaking: "gapirmoqda",
    translated: "tarjima",
    yourLanguage: "Sizning tilingiz",
    partnerLanguage: "Sherik tili",
    connecting: "Ulanmoqda...",
    videoConnecting: "Video ulanmoqda...",
    voiceSpeaking: "Tarjima eshitilmoqda",
    socketOffline: "Server bilan aloqa uzildi",
    ended: "Tugadi",
    shareLink: "Havolani sherigingizga yuboring",
    callEnded: "Qo'ng'iroq tugadi",
    callEndedDesc: "Sherik chiqib ketdi yoki qo'ng'iroq yakunlandi",
    backToDashboard: "Boshqaruv paneliga qaytish",
    mediaDenied: "Kamera yoki mikrofon ruxsati kerak",
    mediaDeniedDesc: "Brauzer sozlamalaridan kamera va mikrofonni yoqing",
    roomFull: "Xona to'liq",
    roomFullDesc: "Bu xonada allaqachon 2 kishi bor",
    roomError: "Ulanish xatosi",
    browserUnsupported: "Tarjima uchun Chrome yoki Edge kerak",
    browserUnsupportedDesc: "Nutqni tanish faqat Chrome/Edge brauzerlarida ishlaydi",
    voiceOn: "Ovozli tarjima yoqish",
    voiceOff: "Ovozli tarjima o'chirish",
    aiActive: "AI faol",
    aiPowered: "Aqlli tarjima",
    translationInfoFull: "Nutqni eshitadi, tarjima qiladi va ovozli aytadi. Siz o'z tilingizda gapiring — sherigingiz o'z tilida ko'radi va eshitadi.",
    joinError: "Xona topilmadi yoki to'liq",
    createRoomDesc: "Havola yuboring — sherigingiz xonaga qo'shiladi",
    joinRoomDesc: "Xona kodini kiriting yoki havoladan o'ting",
    translationInfo: "Qo'ng'iroq paytida sherigingiz boshqa tilde gapirsa, AI avtomatik tarjima qiladi.",
    dialNumber: "Raqam tering",
    dialer: "Terish",
    history: "Tarix",
    yourNumber: "Sizning raqamingiz",
    numberNotFound: "Raqam topilmadi",
    ringing: "Jiringlayapti...",
    incomingCall: "Kiruvchi qo'ng'iroq",
    acceptCall: "Qabul qilish",
    rejectCall: "Rad etish",
    textTranslation: "Matn",
    voiceTranslation: "Ovoz",
    youSaid: "Siz aytdingiz",
    micDeniedDesc: "Brauzer sozlamalaridan mikrofonni yoqing",
    vanityNumbers: "Chiroyli raqamlar",
    vanityDesc: "Maxsus 9 xonali raqam sotib oling",
    browseNumbers: "Raqamlarni ko'rish",
    buy: "Sotib olish",
    premiumNumber: "Premium raqam",
    noNumbersAvailable: "Mavjud raqamlar yo'q",
    unknown: "Noma'lum",
    recents: "So'nggi",
    keypad: "Klaviatura",
    contacts: "Kontaktlar",
    roomTab: "Xona",
    roomInfo: "Xona orqali havola yuboring — sherigingiz linkdan qo'shiladi. Raqam terishdan mustaqil ishlaydi.",
    roomLinkReady: "Xona tayyor — havolani yuboring",
    cancelCall: "Bekor qilish",
    waitingForAnswer: "Javob kutilmoqda...",
    enableNotifications: "Bildirishnomalar yoqish",
    noContacts: "Kontaktlar yo'q",
    noContactsDesc: "Qo'ng'iroq qilganingizdan keyin shu yerda ko'rinadi",
    loadError: "Ma'lumotlarni yuklab bo'lmadi",
    dialError: "Qo'ng'iroq boshlanmadi",
    settings: "Sozlamalar",
    profile: "Profil",
    save: "Saqlash",
    saved: "Saqlandi!",
    statusAvailable: "Mavjud",
    statusBusy: "Band",
    statusDnd: "Bezovta qilinmasin",
    statusAway: "Uzoqda",
    bio: "Holat xabari",
    addContact: "Kontakt qo'shish",
    editContact: "Tahrirlash",
    deleteContact: "O'chirish",
    favorite: "Sevimli",
    favorites: "Sevimlilar",
    notes: "Eslatmalar",
    block: "Bloklash",
    unblock: "Blokdan chiqarish",
    blocked: "Bloklangan",
    callDetail: "Qo'ng'iroq tafsilotlari",
    duration: "Davomiylik",
    transcript: "Transkript",
    summary: "Xulosa",
    noTranscript: "Transkript yo'q",
    missedCalls: "O'tkazib yuborilgan",
    quickMessage: "Tezkor xabar",
    sendMessage: "Xabar yuborish",
    messages: "Xabarlar",
    noMessages: "Xabarlar yo'q",
    messageSent: "Xabar yuborildi",
    typeMessage: "Xabar yozing...",
    online: "Onlayn",
    offline: "Oflayn",
    speedDial: "Tez terish",
    addToContacts: "Kontaktlarga qo'shish",
    callHistory: "Qo'ng'iroq tarixi",
    close: "Yopish",
  },
  ru: {
    appName: "Tcall",
    tagline: "Общайтесь с миром без языковых барьеров",
    login: "Вход",
    register: "Регистрация",
    email: "Email",
    password: "Пароль",
    name: "Ваше имя",
    language: "Ваш язык",
    startCall: "Начать звонок",
    joinCall: "Присоединиться",
    roomId: "Код комнаты",
    dashboard: "Панель управления",
    logout: "Выход",
    waiting: "Ожидание собеседника...",
    connected: "Подключено",
    endCall: "Завершить звонок",
    mute: "Выключить микрофон",
    unmute: "Включить микрофон",
    videoOff: "Выключить камеру",
    videoOn: "Включить камеру",
    translation: "Перевод в реальном времени",
    copyLink: "Копировать ссылку",
    copied: "Скопировано!",
    createRoom: "Создать комнату",
    recentCalls: "Недавние звонки",
    noCalls: "Звонков пока нет",
    speaking: "говорит",
    translated: "перевод",
    yourLanguage: "Ваш язык",
    partnerLanguage: "Язык собеседника",
    connecting: "Подключение...",
    videoConnecting: "Подключение видео...",
    voiceSpeaking: "Воспроизведение перевода",
    socketOffline: "Связь с сервером потеряна",
    ended: "Завершено",
    shareLink: "Отправьте ссылку собеседнику",
    callEnded: "Звонок завершён",
    callEndedDesc: "Собеседник вышел или звонок завершён",
    backToDashboard: "Вернуться в панель",
    mediaDenied: "Нужен доступ к камере и микрофону",
    mediaDeniedDesc: "Разрешите камеру и микрофон в настройках браузера",
    roomFull: "Комната заполнена",
    roomFullDesc: "В этой комнате уже 2 человека",
    roomError: "Ошибка подключения",
    browserUnsupported: "Для перевода нужен Chrome или Edge",
    browserUnsupportedDesc: "Распознавание речи работает только в Chrome/Edge",
    voiceOn: "Включить голосовой перевод",
    voiceOff: "Выключить голосовой перевод",
    aiActive: "AI активен",
    aiPowered: "Умный перевод",
    translationInfoFull: "Слушает речь, переводит и озвучивает. Говорите на своём языке — собеседник видит и слышит на своём.",
    joinError: "Комната не найдена или заполнена",
    createRoomDesc: "Создайте комнату и отправьте ссылку собеседнику",
    joinRoomDesc: "Введите код комнаты или перейдите по ссылке",
    translationInfo: "Во время звонка AI автоматически переводит речь собеседника.",
    dialNumber: "Наберите номер",
    dialer: "Набор",
    history: "История",
    yourNumber: "Ваш номер",
    numberNotFound: "Номер не найден",
    ringing: "Звонит...",
    incomingCall: "Входящий звонок",
    acceptCall: "Принять",
    rejectCall: "Отклонить",
    textTranslation: "Текст",
    voiceTranslation: "Голос",
    youSaid: "Вы сказали",
    micDeniedDesc: "Разрешите микрофон в настройках браузера",
    vanityNumbers: "Красивые номера",
    vanityDesc: "Купите особый 9-значный номер",
    browseNumbers: "Смотреть номера",
    buy: "Купить",
    premiumNumber: "Премиум номер",
    noNumbersAvailable: "Нет доступных номеров",
    unknown: "Неизвестно",
    recents: "Недавние",
    keypad: "Клавиши",
    contacts: "Контакты",
    roomTab: "Комната",
    roomInfo: "Отправьте ссылку — собеседник присоединится по ней. Работает независимо от набора номера.",
    roomLinkReady: "Комната готова — отправьте ссылку",
    cancelCall: "Отменить",
    waitingForAnswer: "Ожидание ответа...",
    enableNotifications: "Включить уведомления",
    noContacts: "Нет контактов",
    noContactsDesc: "Появятся после первого звонка",
    loadError: "Не удалось загрузить данные",
    dialError: "Не удалось начать звонок",
    settings: "Настройки",
    profile: "Профиль",
    save: "Сохранить",
    saved: "Сохранено!",
    statusAvailable: "Доступен",
    statusBusy: "Занят",
    statusDnd: "Не беспокоить",
    statusAway: "Отошёл",
    bio: "Статус",
    addContact: "Добавить контакт",
    editContact: "Изменить",
    deleteContact: "Удалить",
    favorite: "Избранное",
    favorites: "Избранные",
    notes: "Заметки",
    block: "Заблокировать",
    unblock: "Разблокировать",
    blocked: "Заблокирован",
    callDetail: "Детали звонка",
    duration: "Длительность",
    transcript: "Транскрипт",
    summary: "Резюме",
    noTranscript: "Нет транскрипта",
    missedCalls: "Пропущенные",
    quickMessage: "Быстрое сообщение",
    sendMessage: "Отправить",
    messages: "Сообщения",
    noMessages: "Нет сообщений",
    messageSent: "Сообщение отправлено",
    typeMessage: "Введите сообщение...",
    online: "Онлайн",
    offline: "Офлайн",
    speedDial: "Быстрый набор",
    addToContacts: "В контакты",
    callHistory: "История звонков",
    close: "Закрыть",
  },
  en: {
    appName: "Tcall",
    tagline: "Talk to the world without language barriers",
    login: "Login",
    register: "Register",
    email: "Email",
    password: "Password",
    name: "Your name",
    language: "Your language",
    startCall: "Start Call",
    joinCall: "Join Call",
    roomId: "Room code",
    dashboard: "Dashboard",
    logout: "Logout",
    waiting: "Waiting for partner...",
    connected: "Connected",
    endCall: "End Call",
    mute: "Mute",
    unmute: "Unmute",
    videoOff: "Turn off camera",
    videoOn: "Turn on camera",
    translation: "Real-time translation",
    copyLink: "Copy link",
    copied: "Copied!",
    createRoom: "Create room",
    recentCalls: "Recent calls",
    noCalls: "No calls yet",
    speaking: "speaking",
    translated: "translation",
    yourLanguage: "Your language",
    partnerLanguage: "Partner language",
    connecting: "Connecting...",
    videoConnecting: "Connecting video...",
    voiceSpeaking: "Playing translation",
    socketOffline: "Server connection lost",
    ended: "Ended",
    shareLink: "Share the link with your partner",
    callEnded: "Call ended",
    callEndedDesc: "Your partner left or the call has ended",
    backToDashboard: "Back to dashboard",
    mediaDenied: "Camera and microphone access required",
    mediaDeniedDesc: "Please allow camera and microphone in browser settings",
    roomFull: "Room is full",
    roomFullDesc: "This room already has 2 participants",
    roomError: "Connection error",
    browserUnsupported: "Chrome or Edge required for translation",
    browserUnsupportedDesc: "Speech recognition only works in Chrome/Edge browsers",
    voiceOn: "Enable voice translation",
    voiceOff: "Disable voice translation",
    aiActive: "AI active",
    aiPowered: "Smart translation",
    translationInfoFull: "Listens, translates and speaks aloud. Talk in your language — your partner sees and hears in theirs.",
    joinError: "Room not found or full",
    createRoomDesc: "Create a video call room and share the link with your partner",
    joinRoomDesc: "Enter room code or use the invitation link",
    translationInfo: "During the call, AI automatically translates your partner's speech.",
    dialNumber: "Enter number",
    dialer: "Dial",
    history: "History",
    yourNumber: "Your number",
    numberNotFound: "Number not found",
    ringing: "Ringing...",
    incomingCall: "Incoming call",
    acceptCall: "Accept",
    rejectCall: "Decline",
    textTranslation: "Text",
    voiceTranslation: "Voice",
    youSaid: "You said",
    micDeniedDesc: "Please allow microphone in browser settings",
    vanityNumbers: "Vanity numbers",
    vanityDesc: "Buy a special 9-digit number",
    browseNumbers: "Browse numbers",
    buy: "Buy",
    premiumNumber: "Premium number",
    noNumbersAvailable: "No numbers available",
    unknown: "Unknown",
    recents: "Recents",
    keypad: "Keypad",
    contacts: "Contacts",
    roomTab: "Room",
    roomInfo: "Share the link — your partner joins via URL. Works independently from dialing.",
    roomLinkReady: "Room ready — share the link",
    cancelCall: "Cancel",
    waitingForAnswer: "Waiting for answer...",
    enableNotifications: "Enable notifications",
    noContacts: "No contacts",
    noContactsDesc: "Appear here after your first call",
    loadError: "Failed to load data",
    dialError: "Could not start call",
    settings: "Settings",
    profile: "Profile",
    save: "Save",
    saved: "Saved!",
    statusAvailable: "Available",
    statusBusy: "Busy",
    statusDnd: "Do Not Disturb",
    statusAway: "Away",
    bio: "Status message",
    addContact: "Add contact",
    editContact: "Edit",
    deleteContact: "Delete",
    favorite: "Favorite",
    favorites: "Favorites",
    notes: "Notes",
    block: "Block",
    unblock: "Unblock",
    blocked: "Blocked",
    callDetail: "Call details",
    duration: "Duration",
    transcript: "Transcript",
    summary: "Summary",
    noTranscript: "No transcript",
    missedCalls: "Missed",
    quickMessage: "Quick message",
    sendMessage: "Send message",
    messages: "Messages",
    noMessages: "No messages",
    messageSent: "Message sent",
    typeMessage: "Type a message...",
    online: "Online",
    offline: "Offline",
    speedDial: "Speed dial",
    addToContacts: "Add to contacts",
    callHistory: "Call history",
    close: "Close",
  },
} as const;

export type UILocale = keyof typeof UI_TEXT;

export function getUI(lang: string): (typeof UI_TEXT)[UILocale] {
  if (lang in UI_TEXT) return UI_TEXT[lang as UILocale];
  return UI_TEXT.en;
}
