import { LANGUAGES, SPEECH_LOCALES, type LanguageCode } from "./languages-list";

export { LANGUAGES, SPEECH_LOCALES, type LanguageCode };

export function getLanguage(code: string) {
  return LANGUAGES.find((l) => l.code === code) ?? LANGUAGES[0];
}

export function getLanguageName(code: string) {
  return getLanguage(code).name;
}

export function isSupportedLanguage(code: string): boolean {
  return LANGUAGES.some((l) => l.code === code);
}

export const UI_TEXT = {
  uz: {
    appName: "Tcall",
    tagline: "Dunyo bilan til chegarasisiz gaplashing",
    login: "Kirish",
    register: "Ro'yxatdan o'tish",
    email: "Email",
    password: "Parol",
    name: "Ismingiz",
    language: "Sizning tilingiz",
    startCall: "Qo'ng'iroq boshlash",
    joinCall: "Qo'ng'iroqqa qo'shilish",
    roomId: "Xona kodi",
    dashboard: "Boshqaruv paneli",
    logout: "Chiqish",
    waiting: "Sherik kutilmoqda...",
    connected: "Ulandi",
    endCall: "Qo'ng'iroqni tugatish",
    mute: "Ovozni o'chirish",
    unmute: "Ovozni yoqish",
    videoOff: "Kamerani o'chirish",
    videoOn: "Kamerani yoqish",
    translation: "Real-time tarjima",
    copyLink: "Havolani nusxalash",
    copied: "Nusxalandi!",
    createRoom: "Yangi xona yaratish",
    recentCalls: "So'nggi qo'ng'iroqlar",
    noCalls: "Hali qo'ng'iroqlar yo'q",
    speaking: "gapirmoqda",
    translated: "tarjima",
    yourLanguage: "Sizning tilingiz",
    partnerLanguage: "Sherik tili",
    connecting: "Ulanmoqda...",
    videoConnecting: "Video ulanmoqda...",
    voiceSpeaking: "Tarjima eshitilmoqda",
    socketOffline: "Server bilan aloqa uzildi",
    reconnecting: "Avtomatik ulanmoqda...",
    ended: "Tugadi",
    shareLink: "Havolani sherigingizga yuboring",
    shareLinkShort: "Ulashish",
    copyLinkShort: "Nusxalash",
    enterRoom: "Xonaga kirish",
    createNewRoom: "Yangi xona yaratish",
    roomHeroTitle: "Qo'ng'iroq xonasi",
    roomHeroDesc: "Havola yuboring — AI real vaqtda tarjima qiladi",
    roomCodePlaceholder: "XONA KODI",
    loading: "Yuklanmoqda...",
    callEnded: "Qo'ng'iroq tugadi",
    callEndedDesc: "Sherik chiqib ketdi yoki qo'ng'iroq yakunlandi",
    backToDashboard: "Boshqaruv paneliga qaytish",
    returningToDashboard: "Boshqaruv panelga qaytilmoqda...",
    mediaDenied: "Mikrofon ruxsati kerak",
    mediaDeniedDesc: "Brauzer sozlamalaridan mikrofonni yoqing",
    micPermissionTitle: "Mikrofon ruxsati",
    micPermissionDesc: "Qo'ng'iroq uchun mikrofon kerak. «Ruxsat berish» ni bosing — keyingi safar avtomatik ishlaydi.",
    micAllow: "Ruxsat berish",
    micPermissionWaiting: "Ruxsat so'ralmoqda...",
    micTapTitle: "Qo'ng'iroqni boshlang",
    micTapDesc: "Mikrofon ruxsati allaqachon berilgan. Davom etish uchun bosing.",
    micTapBtn: "Davom etish",
    micDeniedTitle: "Mikrofon bloklangan",
    micRetry: "Qayta urinish",
    micSettingsHint: "iPhone: Sozlamalar → Safari → Mikrofon → Ruxsat berish",
    roomFull: "Xona to'liq",
    roomFullDesc: "Bu xonada allaqachon 2 kishi bor",
    roomError: "Ulanish xatosi",
    browserUnsupported: "Tarjima uchun Chrome yoki Edge kerak",
    browserUnsupportedDesc: "Nutqni tanish faqat Chrome/Edge brauzerlarida ishlaydi",
    voiceOn: "Ovozli tarjima yoqish",
    voiceOff: "Ovozli tarjima o'chirish",
    aiActive: "AI faol",
    aiPowered: "Aqlli tarjima",
    translationInfoFull: "Nutqni eshitadi, tarjima qiladi va ovozli aytadi. Siz o'z tilingizda gapiring — sherigingiz o'z tilida ko'radi va eshitadi.",
    joinError: "Xona topilmadi yoki to'liq",
    createRoomDesc: "Havola yuboring — sherigingiz xonaga qo'shiladi",
    joinRoomDesc: "Xona kodini kiriting yoki havoladan o'ting",
    translationInfo: "Qo'ng'iroq paytida sherigingiz boshqa tilde gapirsa, AI avtomatik tarjima qiladi.",
    dialNumber: "Raqam tering",
    dialer: "Terish",
    history: "Tarix",
    yourNumber: "Sizning raqamingiz",
    numberNotFound: "Raqam topilmadi",
    ringing: "Jiringlayapti...",
    incomingCall: "Kiruvchi qo'ng'iroq",
    acceptCall: "Qabul qilish",
    rejectCall: "Rad etish",
    textTranslation: "Matn",
    voiceTranslation: "Ovoz",
    youSaid: "Siz aytdingiz",
    minimizeCall: "Pastga yig'ish",
    expandCall: "Qo'ng'iroqni ochish",
    callInProgress: "Faol qo'ng'iroq",
    micDeniedDesc: "Brauzer sozlamalaridan mikrofonni yoqing",
    vanityNumbers: "Raqamlar",
    vanityDesc: "Chiroyli raqam tanlang — admin tasdiqlaguncha ID o'zgarmaydi",
    browseNumbers: "Raqamlarni ko'rish",
    buy: "Sotib olish",
    premiumNumber: "Premium raqam",
    noNumbersAvailable: "Mavjud raqamlar yo'q",
    vanityCatalog: "Katalog",
    vanityCustomDial: "Raqam terish",
    vanityCustomDesc: "O'zingiz xohlagan 9 xonali raqamni tering",
    vanitySearchPlaceholder: "Raqam qidirish...",
    vanityAvailable: "Bo'sh — sotib olish mumkin",
    vanityTaken: "Band",
    vanityRequestSent: "So'rov yuborildi",
    vanityRequestHint: "Admin tasdiqlaguncha joriy raqamingiz saqlanadi",
    vanityPendingTitle: "So'rov kutilmoqda",
    vanityPendingNote: "Admin tasdiqlaguncha raqamingiz o'zgarmaydi. Telegram orqali bog'laning.",
    selectedNumber: "Tanlangan raqam",
    contactAdmin: "Admin bilan bog'lanish",
    close: "Yopish",
    all: "Hammasi",
    unknown: "Noma'lum",
    recents: "So'nggi",
    keypad: "Terish",
    contacts: "Kontaktlar",
    friendsTab: "Do'stlar",
    friends: "Do'stlar",
    searchUser: "Qidiruv",
    search: "Qidirish",
    searchByIdPlaceholder: "123456789",
    userNotFound: "Foydalanuvchi topilmadi",
    addFriend: "Do'st qo'shish",
    alreadyFriend: "Do'stingiz",
    noFriends: "Do'stlar yo'q",
    noFriendsDesc: "ID orqali qidiring va do'st qo'shing",
    removeFriend: "O'chirish",
    blacklist: "Qora ro'yxat",
    blacklistDesc: "Bloklanganlar sizga qo'ng'iroq va SMS yubora olmaydi",
    blacklistEmpty: "Qora ro'yxat bo'sh",
    blockedYou: "Sizni bloklagan",
    blockedCantCall: "Bloklangan — qo'ng'iroq qilib bo'lmaydi",
    blockedCantMessage: "Bloklangan — SMS yuborib bo'lmaydi",
    unknownUser: "Noma'lum",
    call: "Qo'ng'iroq",
    roomTab: "Xona",
    roomInfo: "Xona orqali havola yuboring — sherigingiz linkdan qo'shiladi. Raqam terishdan mustaqil ishlaydi.",
    roomLinkReady: "Xona tayyor — havolani yuboring",
    cancelCall: "Bekor qilish",
    waitingForAnswer: "Javob kutilmoqda...",
    enableNotifications: "Bildirishnomalar yoqish",
    noContacts: "Kontaktlar yo'q",
    noContactsDesc: "Qo'ng'iroq qilganingizdan keyin shu yerda ko'rinadi",
    loadError: "Ma'lumotlarni yuklab bo'lmadi",
    dialError: "Qo'ng'iroq boshlanmadi",
    settings: "Sozlamalar",
    profile: "Profil",
    save: "Saqlash",
    saved: "Saqlandi!",
    statusAvailable: "Mavjud",
    statusBusy: "Band",
    statusDnd: "Bezovta qilinmasin",
    statusAway: "Uzoqda",
    bio: "Holat xabari",
    addContact: "Kontakt qo'shish",
    editContact: "Tahrirlash",
    deleteContact: "O'chirish",
    favorite: "Sevimli",
    favorites: "Sevimlilar",
    notes: "Eslatmalar",
    block: "Bloklash",
    unblock: "Blokdan chiqarish",
    blocked: "Bloklangan",
    requestUnblock: "Blokdan chiqishni so'rash",
    unblockRequestSent: "Iltimos yuborildi — javob kutilmoqda",
    unblockRequestIncoming: "Blokdan chiqish so'rovi",
    acceptUnblock: "Ruxsat berish",
    rejectUnblock: "Rad etish",
    incomingUnblockRequests: "Kiruvchi so'rovlar",
    viewProfile: "Profil",
    tier_free: "Oddiy",
    tier_bronze: "Bronza",
    tier_silver: "Kumush",
    tier_silver_plus: "Kumush +",
    tier_silver_plus_plus: "Kumush ++",
    tier_gold: "Oltin",
    tier_gold_plus: "Oltin +",
    tier_gold_plus_plus: "Oltin ++",
    tier_platinum: "Platin",
    tier_platinum_plus: "Platin +",
    tier_platinum_plus_plus: "Platin ++",
    tier_platinum_premium: "Platin Premium",
    tier_platinum_premium_plus: "Platin Premium +",
    tier_platinum_premium_plus_plus: "Platin Premium ++",
    tier_vip: "VIP",
    vanityFreeNumber: "Oddiy raqam — bepul, sotib olish shart emas",
    profileEdit: "Profilni tahrirlash",
    profilePhoto: "Profil rasmi",
    changePhoto: "Rasmni o'zgartirish",
    removePhoto: "Rasmni o'chirish",
    profileYearsOld: "yosh",
    profileAge: "Yosh",
    profileCity: "Shahar",
    profileCountry: "Mamlakat",
    profileAddress: "Manzil",
    profileWorkplace: "Ish joyi",
    profileEducation: "O'qish joyi",
    profileGraduatedFrom: "Bitirgan joyi",
    profileProfession: "Kasb",
    profileInterests: "Qiziqishlar",
    profileSkills: "Bilim va ko'nikmalar",
    profileAbout: "O'zim haqimda",
    profileDetails: "Ma'lumotlar",
    profileNoDetails: "Ma'lumot kiritilmagan",
    profileStatusLine: "Qisqa holat",
    groupPhoto: "Guruh rasmi",
    changeGroupPhoto: "Guruh rasmini o'zgartirish",
    uploadPhoto: "Rasm yuklash",
    photoUploading: "Yuklanmoqda...",
    copyrightCreated: "FJSTI inkubatsiya va akseleratsiya tomonidan yaratilgan",
    copyrightRights: "Barcha huquqlar himoyalangan",
    callDetail: "Qo'ng'iroq tafsilotlari",
    duration: "Davomiylik",
    transcript: "Transkript",
    summary: "Xulosa",
    noTranscript: "Transkript yo'q",
    missedCalls: "O'tkazib yuborilgan",
    quickMessage: "Tezkor xabar",
    sendMessage: "Xabar yuborish",
    messages: "Xabarlar",
    noMessages: "Xabarlar yo'q",
    messageSent: "Xabar yuborildi",
    typeMessage: "Xabar yozing...",
    newChat: "Yangi chat",
    newGroup: "Guruh",
    startChat: "Chat boshlash",
    groupName: "Guruh nomi",
    groupMembersHint: "A'zo raqamlari (vergul yoki yangi qator bilan)",
    createGroup: "Guruh yaratish",
    chatMembers: "a'zo",
    chatEmptyThread: "Birinchi xabarni yuboring — tarjima avtomatik bo'ladi",
    chatTranslationAuto: "Xabarlar avtomatik tarjima qilinadi",
    chatTranslatedFrom: "Tarjima",
    chatHint: "Raqam bo'yicha chat yoki guruh yarating. Xabarlar qabul qiluvchi tiliga tarjima qilinadi.",
    viewOriginal: "Asl matnni ko'rish",
    viewTranslation: "Tarjimani ko'rish",
    chatFile: "Fayl",
    chatUploading: "Yuklanmoqda...",
    chatUploadFailed: "Rasm yoki video yuborilmadi",
    chatOpenFile: "Faylni ochish",
    chatPhoto: "Rasm",
    chatVideo: "Video",
    chatLeaveGroup: "Guruhdan chiqish",
    chatDeleteChat: "Chatni o'chirish",
    chatDeleteGroup: "Guruhni o'chirish",
    chatAddMembers: "A'zo qo'shish",
    chatManage: "Boshqarish",
    chatConfirmLeave: "Chatdan chiqasizmi?",
    chatConfirmDeleteGroup: "Guruh butunlay o'chirilsinmi?",
    chatMembersAdded: "A'zolar qo'shildi",
    chatActionFailed: "Amal bajarilmadi",
    chatViewMembers: "A'zolar",
    chatOwner: "Egasi",
    chatAdmin: "Admin",
    chatMember: "A'zo",
    chatMakeAdmin: "Admin qilish",
    chatRemoveAdmin: "Admindan olish",
    chatMakeOwner: "Egasi qilish",
    chatRemoveMember: "Guruhdan chiqarish",
    chatConfirmRemoveMember: "Bu a'zoni guruhdan chiqarasizmi?",
    chatConfirmMakeAdmin: "Admin qilinsinmi?",
    chatConfirmMakeOwner: "Guruh egasi o'zgartirilsinmi?",
    chatConfirmDeleteChat: "Chat o'chirilsinmi?",
    chatRenameGroup: "Guruh nomi",
    chatGroupSettings: "Guruh sozlamalari",
    chatSettings: "Chat sozlamalari",
    chatSave: "Saqlash",
    chatNoMembersFound: "Raqamlar topilmadi",
    chatOnlyAdminAdd: "Faqat admin qo'sha oladi",
    vanityInvalidFirstDigit: "Raqam 1–9 bilan boshlanishi kerak",
    roomParticipants: "Xonada",
    roomWaitingGuest: "Sherik kutilmoqda...",
    roomGuestJoined: "Sherik qo'shildi",
    dialInvalidFirstDigit: "Birinchi raqam 1–9 bo'lishi kerak",
    online: "Onlayn",
    offline: "Oflayn",
    speedDial: "Tez terish",
    addToContacts: "Kontaktlarga qo'shish",
    callHistory: "Qo'ng'iroq tarixi",
    interpreterTab: "Tarjimon",
    interpreterTitle: "Real vaqt tarjimon",
    interpreterDesc: "Telefonni ikki kishi orasida tuting — gapirganingiz OpenAI ovozida tarjima qilinadi",
    interpreterMyLang: "Mening tilim",
    interpreterTheirLang: "Sherik tili",
    interpreterSwapLang: "Til almashtirish",
    interpreterISpeak: "Men gapiraman",
    interpreterTheySpeak: "U gapiradi",
    interpreterHoldToTalk: "Ushlab gapiring (kamida 1 soniya)",
    interpreterReleaseHint: "Kamida 1 soniya ushlab gapiring — qoldirganda ovozli tarjima chiqadi",
    interpreterProcessing: "Tarjima qilinmoqda...",
    interpreterListening: "Tinglanmoqda...",
    interpreterSpeaking: "Tarjima ovozi",
    interpreterClearHistory: "Tarixni tozalash",
    interpreterStart: "Mikrofonni yoqish",
    interpreterStop: "To'xtatish",
    interpreterMicRequired: "Mikrofon ruxsati kerak — brauzer sozlamalaridan yoqing",
    interpreterNoSpeech: "Ovoz aniqlanmadi — biroz uzoqroq ushlab gapiring",
    interpreterError: "Tarjima xatosi — qayta urinib ko'ring",
    interpreterSameLang: "Ikkala til bir xil — boshqa til tanlang",
    interpreterHint: "Mikrofonni yoqing. Ushlab gapiring — tarjima ovozda eshitiladi.",
    interpreterSessionActive: "Faol",
    interpreterVoiceOn: "Ovoz yoqilgan",
    interpreterVoiceOff: "Ovoz o'chirilgan",
  },
  ru: {
    appName: "Tcall",
    tagline: "Общайтесь с миром без языковых барьеров",
    login: "Вход",
    register: "Регистрация",
    email: "Email",
    password: "Пароль",
    name: "Ваше имя",
    language: "Ваш язык",
    startCall: "Начать звонок",
    joinCall: "Присоединиться",
    roomId: "Код комнаты",
    dashboard: "Панель управления",
    logout: "Выход",
    waiting: "Ожидание собеседника...",
    connected: "Подключено",
    endCall: "Завершить звонок",
    mute: "Выключить микрофон",
    unmute: "Включить микрофон",
    videoOff: "Выключить камеру",
    videoOn: "Включить камеру",
    translation: "Перевод в реальном времени",
    copyLink: "Копировать ссылку",
    copied: "Скопировано!",
    createRoom: "Создать комнату",
    recentCalls: "Недавние звонки",
    noCalls: "Звонков пока нет",
    speaking: "говорит",
    translated: "перевод",
    yourLanguage: "Ваш язык",
    partnerLanguage: "Язык собеседника",
    connecting: "Подключение...",
    videoConnecting: "Подключение видео...",
    voiceSpeaking: "Воспроизведение перевода",
    socketOffline: "Связь с сервером потеряна",
    reconnecting: "Автоподключение...",
    ended: "Завершено",
    shareLink: "Отправьте ссылку собеседнику",
    shareLinkShort: "Поделиться",
    copyLinkShort: "Копировать",
    enterRoom: "Войти в комнату",
    createNewRoom: "Создать новую комнату",
    roomHeroTitle: "Комната для звонка",
    roomHeroDesc: "Отправьте ссылку — AI переводит в реальном времени",
    roomCodePlaceholder: "КОД КОМНАТЫ",
    loading: "Загрузка...",
    callEnded: "Звонок завершён",
    callEndedDesc: "Собеседник вышел или звонок завершён",
    backToDashboard: "Вернуться в панель",
    returningToDashboard: "Возврат в панель...",
    mediaDenied: "Нужен доступ к микрофону",
    mediaDeniedDesc: "Разрешите микрофон в настройках браузера",
    micPermissionTitle: "Доступ к микрофону",
    micPermissionDesc: "Для звонка нужен микрофон. Нажмите «Разрешить» — в следующий раз будет автоматически.",
    micAllow: "Разрешить",
    micPermissionWaiting: "Запрос разрешения...",
    micTapTitle: "Начать звонок",
    micTapDesc: "Доступ к микрофону уже есть. Нажмите, чтобы продолжить.",
    micTapBtn: "Продолжить",
    micDeniedTitle: "Микрофон заблокирован",
    micRetry: "Повторить",
    micSettingsHint: "iPhone: Настройки → Safari → Микрофон → Разрешить",
    roomFull: "Комната заполнена",
    roomFullDesc: "В этой комнате уже 2 человека",
    roomError: "Ошибка подключения",
    browserUnsupported: "Для перевода нужен Chrome или Edge",
    browserUnsupportedDesc: "Распознавание речи работает только в Chrome/Edge",
    voiceOn: "Включить голосовой перевод",
    voiceOff: "Выключить голосовой перевод",
    aiActive: "AI активен",
    aiPowered: "Умный перевод",
    translationInfoFull: "Слушает речь, переводит и озвучивает. Говорите на своём языке — собеседник видит и слышит на своём.",
    joinError: "Комната не найдена или заполнена",
    createRoomDesc: "Создайте комнату и отправьте ссылку собеседнику",
    joinRoomDesc: "Введите код комнаты или перейдите по ссылке",
    translationInfo: "Во время звонка AI автоматически переводит речь собеседника.",
    dialNumber: "Наберите номер",
    dialer: "Набор",
    history: "История",
    yourNumber: "Ваш номер",
    numberNotFound: "Номер не найден",
    ringing: "Звонит...",
    incomingCall: "Входящий звонок",
    acceptCall: "Принять",
    rejectCall: "Отклонить",
    textTranslation: "Текст",
    voiceTranslation: "Голос",
    youSaid: "Вы сказали",
    minimizeCall: "Свернуть",
    expandCall: "Развернуть звонок",
    callInProgress: "Активный звонок",
    micDeniedDesc: "Разрешите микрофон в настройках браузера",
    vanityNumbers: "Номера",
    vanityDesc: "Выберите номер — ID изменится после подтверждения админом",
    browseNumbers: "Смотреть номера",
    buy: "Купить",
    premiumNumber: "Премиум номер",
    noNumbersAvailable: "Нет доступных номеров",
    vanityCatalog: "Каталог",
    vanityCustomDial: "Набрать номер",
    vanityCustomDesc: "Введите желаемый 9-значный номер",
    vanitySearchPlaceholder: "Поиск номера...",
    vanityAvailable: "Свободен",
    vanityTaken: "Занят",
    vanityRequestSent: "Заявка отправлена",
    vanityRequestHint: "До подтверждения админом ваш ID не изменится",
    vanityPendingTitle: "Заявка ожидает",
    vanityPendingNote: "Свяжитесь с админом в Telegram",
    selectedNumber: "Выбранный номер",
    contactAdmin: "Связаться с админом",
    close: "Закрыть",
    all: "Все",
    unknown: "Неизвестно",
    recents: "Недавние",
    keypad: "Набор",
    contacts: "Контакты",
    friendsTab: "Друзья",
    friends: "Друзья",
    searchUser: "Поиск",
    search: "Искать",
    searchByIdPlaceholder: "123456789",
    userNotFound: "Пользователь не найден",
    addFriend: "Добавить в друзья",
    alreadyFriend: "В друзьях",
    noFriends: "Нет друзей",
    noFriendsDesc: "Найдите по ID и добавьте в друзья",
    removeFriend: "Удалить",
    blacklist: "Чёрный список",
    blacklistDesc: "Заблокированные не могут звонить и писать вам",
    blacklistEmpty: "Чёрный список пуст",
    blockedYou: "Заблокировал вас",
    blockedCantCall: "Заблокирован — звонок невозможен",
    blockedCantMessage: "Заблокирован — сообщение невозможно",
    unknownUser: "Неизвестный",
    call: "Звонок",
    roomTab: "Комната",
    roomInfo: "Отправьте ссылку — собеседник присоединится по ней. Работает независимо от набора номера.",
    roomLinkReady: "Комната готова — отправьте ссылку",
    cancelCall: "Отменить",
    waitingForAnswer: "Ожидание ответа...",
    enableNotifications: "Включить уведомления",
    noContacts: "Нет контактов",
    noContactsDesc: "Появятся после первого звонка",
    loadError: "Не удалось загрузить данные",
    dialError: "Не удалось начать звонок",
    settings: "Настройки",
    profile: "Профиль",
    save: "Сохранить",
    saved: "Сохранено!",
    statusAvailable: "Доступен",
    statusBusy: "Занят",
    statusDnd: "Не беспокоить",
    statusAway: "Отошёл",
    bio: "Статус",
    addContact: "Добавить контакт",
    editContact: "Изменить",
    deleteContact: "Удалить",
    favorite: "Избранное",
    favorites: "Избранные",
    notes: "Заметки",
    block: "Заблокировать",
    unblock: "Разблокировать",
    blocked: "Заблокирован",
    requestUnblock: "Запросить разблокировку",
    unblockRequestSent: "Запрос отправлен — ожидайте ответа",
    unblockRequestIncoming: "Запрос на разблокировку",
    acceptUnblock: "Разрешить",
    rejectUnblock: "Отклонить",
    incomingUnblockRequests: "Входящие запросы",
    viewProfile: "Профиль",
    tier_free: "Обычный",
    tier_bronze: "Бронза",
    tier_silver: "Серебро",
    tier_silver_plus: "Серебро +",
    tier_silver_plus_plus: "Серебро ++",
    tier_gold: "Золото",
    tier_gold_plus: "Золото +",
    tier_gold_plus_plus: "Золото ++",
    tier_platinum: "Платина",
    tier_platinum_plus: "Платина +",
    tier_platinum_plus_plus: "Платина ++",
    tier_platinum_premium: "Платина Premium",
    tier_platinum_premium_plus: "Платина Premium +",
    tier_platinum_premium_plus_plus: "Платина Premium ++",
    tier_vip: "VIP",
    vanityFreeNumber: "Обычный номер — бесплатно, покупка не требуется",
    profileEdit: "Редактировать профиль",
    profilePhoto: "Фото профиля",
    changePhoto: "Изменить фото",
    removePhoto: "Удалить фото",
    profileYearsOld: "лет",
    profileAge: "Возраст",
    profileCity: "Город",
    profileCountry: "Страна",
    profileAddress: "Адрес",
    profileWorkplace: "Место работы",
    profileEducation: "Место учёбы",
    profileGraduatedFrom: "Окончил",
    profileProfession: "Профессия",
    profileInterests: "Интересы",
    profileSkills: "Навыки и знания",
    profileAbout: "О себе",
    profileDetails: "Информация",
    profileNoDetails: "Информация не указана",
    profileStatusLine: "Краткий статус",
    groupPhoto: "Фото группы",
    changeGroupPhoto: "Изменить фото группы",
    uploadPhoto: "Загрузить фото",
    photoUploading: "Загрузка...",
    copyrightCreated: "Создано при поддержке инкубации и акселерации FJSTI",
    copyrightRights: "Все права защищены",
    callDetail: "Детали звонка",
    duration: "Длительность",
    transcript: "Транскрипт",
    summary: "Резюме",
    noTranscript: "Нет транскрипта",
    missedCalls: "Пропущенные",
    quickMessage: "Быстрое сообщение",
    sendMessage: "Отправить",
    messages: "Сообщения",
    noMessages: "Нет сообщений",
    messageSent: "Сообщение отправлено",
    typeMessage: "Введите сообщение...",
    newChat: "Новый чат",
    newGroup: "Группа",
    startChat: "Начать чат",
    groupName: "Название группы",
    groupMembersHint: "Номера участников (через запятую или с новой строки)",
    createGroup: "Создать группу",
    chatMembers: "участников",
    chatEmptyThread: "Отправьте первое сообщение — перевод будет автоматическим",
    chatTranslationAuto: "Сообщения переводятся автоматически",
    chatTranslatedFrom: "Перевод",
    chatHint: "Создайте чат по номеру или группу. Сообщения переводятся на язык получателя.",
    viewOriginal: "Показать оригинал",
    viewTranslation: "Показать перевод",
    chatFile: "Файл",
    chatUploading: "Загрузка...",
    chatUploadFailed: "Не удалось отправить фото или видео",
    chatOpenFile: "Открыть файл",
    chatPhoto: "Фото",
    chatVideo: "Видео",
    chatLeaveGroup: "Выйти из группы",
    chatDeleteChat: "Удалить чат",
    chatDeleteGroup: "Удалить группу",
    chatAddMembers: "Добавить участников",
    chatManage: "Управление",
    chatConfirmLeave: "Выйти из чата?",
    chatConfirmDeleteGroup: "Удалить группу полностью?",
    chatMembersAdded: "Участники добавлены",
    chatActionFailed: "Не удалось выполнить",
    chatViewMembers: "Участники",
    chatOwner: "Владелец",
    chatAdmin: "Админ",
    chatMember: "Участник",
    chatMakeAdmin: "Сделать админом",
    chatRemoveAdmin: "Снять админа",
    chatMakeOwner: "Передать владение",
    chatRemoveMember: "Исключить",
    chatConfirmRemoveMember: "Исключить участника из группы?",
    chatConfirmMakeAdmin: "Назначить админом?",
    chatConfirmMakeOwner: "Передать владение группой?",
    chatConfirmDeleteChat: "Удалить чат?",
    chatRenameGroup: "Название группы",
    chatGroupSettings: "Настройки группы",
    chatSettings: "Настройки чата",
    chatSave: "Сохранить",
    chatNoMembersFound: "Номера не найдены",
    chatOnlyAdminAdd: "Только админ может добавлять",
    vanityInvalidFirstDigit: "Номер должен начинаться с 1–9",
    roomParticipants: "В комнате",
    roomWaitingGuest: "Ожидание собеседника...",
    roomGuestJoined: "Собеседник подключился",
    dialInvalidFirstDigit: "Первая цифра должна быть 1–9",
    online: "Онлайн",
    offline: "Офлайн",
    speedDial: "Быстрый набор",
    addToContacts: "В контакты",
    callHistory: "История звонков",
    interpreterTab: "Переводчик",
    interpreterTitle: "Переводчик в реальном времени",
    interpreterDesc: "Держите телефон между вами — речь переводится и озвучивается",
    interpreterMyLang: "Мой язык",
    interpreterTheirLang: "Язык собеседника",
    interpreterSwapLang: "Поменять языки",
    interpreterISpeak: "Я говорю",
    interpreterTheySpeak: "Он/она говорит",
    interpreterHoldToTalk: "Удерживайте",
    interpreterReleaseHint: "Удерживайте кнопку — отпустите для перевода и озвучки",
    interpreterProcessing: "Перевод...",
    interpreterListening: "Слушаю...",
    interpreterSpeaking: "Озвучивание",
    interpreterClearHistory: "Очистить",
    interpreterStart: "Включить микрофон",
    interpreterStop: "Остановить",
    interpreterMicRequired: "Нужен доступ к микрофону",
    interpreterNoSpeech: "Речь не распознана",
    interpreterError: "Ошибка перевода",
    interpreterSameLang: "Языки совпадают — выберите другой",
    interpreterHint: "Держите телефон между вами. Когда говорит собеседник — нажмите «Он/она говорит».",
    interpreterSessionActive: "Активен",
    interpreterVoiceOn: "Голос вкл.",
    interpreterVoiceOff: "Голос выкл.",
  },
  en: {
    appName: "Tcall",
    tagline: "Talk to the world without language barriers",
    login: "Login",
    register: "Register",
    email: "Email",
    password: "Password",
    name: "Your name",
    language: "Your language",
    startCall: "Start Call",
    joinCall: "Join Call",
    roomId: "Room code",
    dashboard: "Dashboard",
    logout: "Logout",
    waiting: "Waiting for partner...",
    connected: "Connected",
    endCall: "End Call",
    mute: "Mute",
    unmute: "Unmute",
    videoOff: "Turn off camera",
    videoOn: "Turn on camera",
    translation: "Real-time translation",
    copyLink: "Copy link",
    copied: "Copied!",
    createRoom: "Create room",
    recentCalls: "Recent calls",
    noCalls: "No calls yet",
    speaking: "speaking",
    translated: "translation",
    yourLanguage: "Your language",
    partnerLanguage: "Partner language",
    connecting: "Connecting...",
    videoConnecting: "Connecting video...",
    voiceSpeaking: "Playing translation",
    socketOffline: "Server connection lost",
    reconnecting: "Reconnecting automatically...",
    ended: "Ended",
    shareLink: "Share the link with your partner",
    shareLinkShort: "Share",
    copyLinkShort: "Copy",
    enterRoom: "Enter room",
    createNewRoom: "Create new room",
    roomHeroTitle: "Call room",
    roomHeroDesc: "Share a link — AI translates in real time",
    roomCodePlaceholder: "ROOM CODE",
    loading: "Loading...",
    callEnded: "Call ended",
    callEndedDesc: "Your partner left or the call has ended",
    backToDashboard: "Back to dashboard",
    returningToDashboard: "Returning to dashboard...",
    mediaDenied: "Microphone access required",
    mediaDeniedDesc: "Please allow microphone in browser settings",
    micPermissionTitle: "Microphone access",
    micPermissionDesc: "Calls need your microphone. Tap Allow — next time it works automatically.",
    micAllow: "Allow microphone",
    micPermissionWaiting: "Requesting permission...",
    micTapTitle: "Start the call",
    micTapDesc: "Microphone access is already granted. Tap to continue.",
    micTapBtn: "Continue",
    micDeniedTitle: "Microphone blocked",
    micRetry: "Try again",
    micSettingsHint: "iPhone: Settings → Safari → Microphone → Allow",
    roomFull: "Room is full",
    roomFullDesc: "This room already has 2 participants",
    roomError: "Connection error",
    browserUnsupported: "Chrome or Edge required for translation",
    browserUnsupportedDesc: "Speech recognition only works in Chrome/Edge browsers",
    voiceOn: "Enable voice translation",
    voiceOff: "Disable voice translation",
    aiActive: "AI active",
    aiPowered: "Smart translation",
    translationInfoFull: "Listens, translates and speaks aloud. Talk in your language — your partner sees and hears in theirs.",
    joinError: "Room not found or full",
    createRoomDesc: "Create a video call room and share the link with your partner",
    joinRoomDesc: "Enter room code or use the invitation link",
    translationInfo: "During the call, AI automatically translates your partner's speech.",
    dialNumber: "Enter number",
    dialer: "Dial",
    history: "History",
    yourNumber: "Your number",
    numberNotFound: "Number not found",
    ringing: "Ringing...",
    incomingCall: "Incoming call",
    acceptCall: "Accept",
    rejectCall: "Decline",
    textTranslation: "Text",
    voiceTranslation: "Voice",
    youSaid: "You said",
    minimizeCall: "Minimize",
    expandCall: "Expand call",
    callInProgress: "Call in progress",
    micDeniedDesc: "Please allow microphone in browser settings",
    vanityNumbers: "Numbers",
    vanityDesc: "Pick a vanity number — ID changes only after admin approval",
    browseNumbers: "Browse numbers",
    buy: "Buy",
    premiumNumber: "Premium number",
    noNumbersAvailable: "No numbers available",
    vanityCatalog: "Catalog",
    vanityCustomDial: "Dial number",
    vanityCustomDesc: "Enter your desired 9-digit number",
    vanitySearchPlaceholder: "Search number...",
    vanityAvailable: "Available",
    vanityTaken: "Taken",
    vanityRequestSent: "Request sent",
    vanityRequestHint: "Your ID won't change until admin approves",
    vanityPendingTitle: "Request pending",
    vanityPendingNote: "Contact admin on Telegram",
    selectedNumber: "Selected number",
    contactAdmin: "Contact admin",
    close: "Close",
    all: "All",
    unknown: "Unknown",
    recents: "Recents",
    keypad: "Keypad",
    contacts: "Contacts",
    friendsTab: "Friends",
    friends: "Friends",
    searchUser: "Search",
    search: "Search",
    searchByIdPlaceholder: "123456789",
    userNotFound: "User not found",
    addFriend: "Add friend",
    alreadyFriend: "Friend",
    noFriends: "No friends",
    noFriendsDesc: "Search by ID and add friends",
    removeFriend: "Remove",
    blacklist: "Block list",
    blacklistDesc: "Blocked users cannot call or message you",
    blacklistEmpty: "Block list is empty",
    blockedYou: "Blocked you",
    blockedCantCall: "Blocked — cannot call",
    blockedCantMessage: "Blocked — cannot message",
    unknownUser: "Unknown",
    call: "Call",
    roomTab: "Room",
    roomInfo: "Share the link — your partner joins via URL. Works independently from dialing.",
    roomLinkReady: "Room ready — share the link",
    cancelCall: "Cancel",
    waitingForAnswer: "Waiting for answer...",
    enableNotifications: "Enable notifications",
    noContacts: "No contacts",
    noContactsDesc: "Appear here after your first call",
    loadError: "Failed to load data",
    dialError: "Could not start call",
    settings: "Settings",
    profile: "Profile",
    save: "Save",
    saved: "Saved!",
    statusAvailable: "Available",
    statusBusy: "Busy",
    statusDnd: "Do Not Disturb",
    statusAway: "Away",
    bio: "Status message",
    addContact: "Add contact",
    editContact: "Edit",
    deleteContact: "Delete",
    favorite: "Favorite",
    favorites: "Favorites",
    notes: "Notes",
    block: "Block",
    unblock: "Unblock",
    blocked: "Blocked",
    requestUnblock: "Request unblock",
    unblockRequestSent: "Request sent — awaiting response",
    unblockRequestIncoming: "Unblock request",
    acceptUnblock: "Allow",
    rejectUnblock: "Decline",
    incomingUnblockRequests: "Incoming requests",
    viewProfile: "Profile",
    tier_free: "Standard",
    tier_bronze: "Bronze",
    tier_silver: "Silver",
    tier_silver_plus: "Silver +",
    tier_silver_plus_plus: "Silver ++",
    tier_gold: "Gold",
    tier_gold_plus: "Gold +",
    tier_gold_plus_plus: "Gold ++",
    tier_platinum: "Platinum",
    tier_platinum_plus: "Platinum +",
    tier_platinum_plus_plus: "Platinum ++",
    tier_platinum_premium: "Platinum Premium",
    tier_platinum_premium_plus: "Platinum Premium +",
    tier_platinum_premium_plus_plus: "Platinum Premium ++",
    tier_vip: "VIP",
    vanityFreeNumber: "Standard number — free, no purchase needed",
    profileEdit: "Edit profile",
    profilePhoto: "Profile photo",
    changePhoto: "Change photo",
    removePhoto: "Remove photo",
    profileYearsOld: "years old",
    profileAge: "Age",
    profileCity: "City",
    profileCountry: "Country",
    profileAddress: "Address",
    profileWorkplace: "Workplace",
    profileEducation: "Education",
    profileGraduatedFrom: "Graduated from",
    profileProfession: "Profession",
    profileInterests: "Interests",
    profileSkills: "Skills & knowledge",
    profileAbout: "About me",
    profileDetails: "Details",
    profileNoDetails: "No details provided",
    profileStatusLine: "Short status",
    groupPhoto: "Group photo",
    changeGroupPhoto: "Change group photo",
    uploadPhoto: "Upload photo",
    photoUploading: "Uploading...",
    copyrightCreated: "Created with support from FJSTI incubation and acceleration",
    copyrightRights: "All rights reserved",
    callDetail: "Call details",
    duration: "Duration",
    transcript: "Transcript",
    summary: "Summary",
    noTranscript: "No transcript",
    missedCalls: "Missed",
    quickMessage: "Quick message",
    sendMessage: "Send message",
    messages: "Messages",
    noMessages: "No messages",
    messageSent: "Message sent",
    typeMessage: "Type a message...",
    newChat: "New chat",
    newGroup: "Group",
    startChat: "Start chat",
    groupName: "Group name",
    groupMembersHint: "Member numbers (comma or newline separated)",
    createGroup: "Create group",
    chatMembers: "members",
    chatEmptyThread: "Send the first message — translation is automatic",
    chatTranslationAuto: "Messages are translated automatically",
    chatTranslatedFrom: "Translation",
    chatHint: "Start a chat by number or create a group. Messages are translated to each recipient's language.",
    viewOriginal: "View original",
    viewTranslation: "View translation",
    chatFile: "File",
    chatUploading: "Uploading...",
    chatUploadFailed: "Could not send photo or video",
    chatOpenFile: "Open file",
    chatPhoto: "Photo",
    chatVideo: "Video",
    chatLeaveGroup: "Leave group",
    chatDeleteChat: "Delete chat",
    chatDeleteGroup: "Delete group",
    chatAddMembers: "Add members",
    chatManage: "Manage",
    chatConfirmLeave: "Leave this chat?",
    chatConfirmDeleteGroup: "Delete this group for everyone?",
    chatMembersAdded: "Members added",
    chatActionFailed: "Action failed",
    chatViewMembers: "Members",
    chatOwner: "Owner",
    chatAdmin: "Admin",
    chatMember: "Member",
    chatMakeAdmin: "Make admin",
    chatRemoveAdmin: "Remove admin",
    chatMakeOwner: "Transfer ownership",
    chatRemoveMember: "Remove from group",
    chatConfirmRemoveMember: "Remove this member from the group?",
    chatConfirmMakeAdmin: "Make admin?",
    chatConfirmMakeOwner: "Transfer group ownership?",
    chatConfirmDeleteChat: "Delete this chat?",
    chatRenameGroup: "Group name",
    chatGroupSettings: "Group settings",
    chatSettings: "Chat settings",
    chatSave: "Save",
    chatNoMembersFound: "Numbers not found",
    chatOnlyAdminAdd: "Only admins can add members",
    vanityInvalidFirstDigit: "Number must start with 1–9",
    roomParticipants: "In room",
    roomWaitingGuest: "Waiting for partner...",
    roomGuestJoined: "Partner joined",
    dialInvalidFirstDigit: "First digit must be 1–9",
    online: "Online",
    offline: "Offline",
    speedDial: "Speed dial",
    addToContacts: "Add to contacts",
    callHistory: "Call history",
    interpreterTab: "Interpreter",
    interpreterTitle: "Live interpreter",
    interpreterDesc: "Hold the phone between you — OpenAI speaks the translation aloud in the target language",
    interpreterMyLang: "My language",
    interpreterTheirLang: "Their language",
    interpreterSwapLang: "Swap languages",
    interpreterISpeak: "I speak",
    interpreterTheySpeak: "They speak",
    interpreterHoldToTalk: "Hold to talk (at least 1 sec)",
    interpreterReleaseHint: "Hold at least 1 second — release for voice translation",
    interpreterProcessing: "Translating...",
    interpreterListening: "Listening...",
    interpreterSpeaking: "Playing translation",
    interpreterClearHistory: "Clear history",
    interpreterStart: "Enable microphone",
    interpreterStop: "Stop",
    interpreterMicRequired: "Microphone access required",
    interpreterNoSpeech: "No speech detected — hold the button a bit longer",
    interpreterError: "Translation error — try again",
    interpreterSameLang: "Both languages are the same — pick different ones",
    interpreterHint: "Enable the mic. Hold to speak — translation plays as voice only.",
    interpreterSessionActive: "Active",
    interpreterVoiceOn: "Voice on",
    interpreterVoiceOff: "Voice off",
  },
} as const;

export type UILocale = keyof typeof UI_TEXT;

export function getUI(lang: string): (typeof UI_TEXT)[UILocale] {
  if (lang in UI_TEXT) return UI_TEXT[lang as UILocale];
  return UI_TEXT.en;
}
