package uz.tcall.ui.util

// AUTO-GENERATED — npm run generate:languages
data class LangOption(val code: String, val label: String)

val TCALL_LANGUAGES: List<LangOption> = listOf(
    LangOption("uz", "O'zbek"),
    LangOption("ru", "Русский"),
    LangOption("en", "English"),
    LangOption("tr", "Türkçe"),
    LangOption("ar", "العربية"),
    LangOption("zh", "中文"),
    LangOption("ko", "한국어"),
    LangOption("ja", "日本語"),
    LangOption("de", "Deutsch"),
    LangOption("fr", "Français"),
    LangOption("es", "Español"),
    LangOption("hi", "हिन्दी"),
    LangOption("tg", "Тоҷикӣ"),
    LangOption("kk", "Қазақ"),
    LangOption("ky", "Кыргыз"),
    LangOption("pt", "Português"),
    LangOption("it", "Italiano"),
    LangOption("pl", "Polski"),
    LangOption("uk", "Українська"),
    LangOption("fa", "فارسی"),
    LangOption("ur", "اردو"),
    LangOption("bn", "বাংলা"),
    LangOption("pa", "ਪੰਜਾਬੀ"),
    LangOption("ta", "தமிழ்"),
    LangOption("te", "తెలుగు"),
    LangOption("mr", "मराठी"),
    LangOption("gu", "ગુજરાતી"),
    LangOption("ml", "മലയാളം"),
    LangOption("id", "Bahasa Indonesia"),
    LangOption("ms", "Bahasa Melayu"),
    LangOption("vi", "Tiếng Việt"),
    LangOption("th", "ไทย"),
    LangOption("my", "မြန်မာ"),
    LangOption("km", "ខ្មែរ"),
    LangOption("lo", "ລາວ"),
    LangOption("ne", "नेपाली"),
    LangOption("si", "සිංහල"),
    LangOption("mn", "Монгол"),
    LangOption("az", "Azərbaycan"),
    LangOption("ka", "ქართული"),
    LangOption("hy", "Հայերեն"),
    LangOption("he", "עברית"),
    LangOption("nl", "Nederlands"),
    LangOption("sv", "Svenska"),
    LangOption("no", "Norsk"),
    LangOption("da", "Dansk"),
    LangOption("fi", "Suomi"),
    LangOption("cs", "Čeština"),
    LangOption("sk", "Slovenčina"),
    LangOption("hu", "Magyar"),
    LangOption("ro", "Română"),
    LangOption("bg", "Български"),
    LangOption("hr", "Hrvatski"),
    LangOption("sr", "Српски"),
    LangOption("sl", "Slovenščina"),
    LangOption("lt", "Lietuvių"),
    LangOption("lv", "Latviešu"),
    LangOption("et", "Eesti"),
    LangOption("sq", "Shqip"),
    LangOption("mk", "Македонски"),
    LangOption("bs", "Bosanski"),
    LangOption("ps", "پښتو"),
    LangOption("sw", "Kiswahili"),
    LangOption("am", "አማርኛ"),
    LangOption("yo", "Yorùbá"),
    LangOption("ha", "Hausa"),
    LangOption("af", "Afrikaans"),
    LangOption("tl", "Filipino"),
    LangOption("be", "Беларуская"),
    LangOption("ca", "Català"),
    LangOption("eu", "Euskara"),
    LangOption("gl", "Galego"),
    LangOption("is", "Íslenska"),
    LangOption("ga", "Gaeilge"),
    LangOption("cy", "Cymraeg"),
    LangOption("mt", "Malti"),
    LangOption("lb", "Lëtzebuergesch"),
    LangOption("ab", "Abkhazian"),
    LangOption("aa", "Afar"),
    LangOption("ak", "Akan"),
    LangOption("tw", "Akan"),
    LangOption("an", "Aragonese"),
    LangOption("as", "Assamese"),
    LangOption("av", "Avaric"),
    LangOption("ae", "Avestan"),
    LangOption("ay", "Aymara"),
    LangOption("bm", "Bambara"),
    LangOption("ba", "Bashkir"),
    LangOption("bh", "Bhojpuri"),
    LangOption("bi", "Bislama"),
    LangOption("br", "Breton"),
    LangOption("ch", "Chamorro"),
    LangOption("ce", "Chechen"),
    LangOption("cu", "Church Slavic"),
    LangOption("cv", "Chuvash"),
    LangOption("kw", "Cornish"),
    LangOption("co", "Corsican"),
    LangOption("cr", "Cree"),
    LangOption("dv", "Divehi"),
    LangOption("dz", "Dzongkha"),
    LangOption("eo", "Esperanto"),
    LangOption("ee", "Ewe"),
    LangOption("fo", "Faroese"),
    LangOption("fj", "Fijian"),
    LangOption("ff", "Fula"),
    LangOption("lg", "Ganda"),
    LangOption("el", "Greek"),
    LangOption("gn", "Guarani"),
    LangOption("ht", "Haitian Creole"),
    LangOption("hz", "Herero"),
    LangOption("ho", "Hiri Motu"),
    LangOption("io", "Ido"),
    LangOption("ig", "Igbo"),
    LangOption("ia", "Interlingua"),
    LangOption("ie", "Interlingue"),
    LangOption("iu", "Inuktitut"),
    LangOption("ik", "Inupiaq"),
    LangOption("jv", "Javanese"),
    LangOption("kl", "Kalaallisut"),
    LangOption("kn", "Kannada"),
    LangOption("kr", "Kanuri"),
    LangOption("ks", "Kashmiri"),
    LangOption("ki", "Kikuyu"),
    LangOption("rw", "Kinyarwanda"),
    LangOption("kv", "Komi"),
    LangOption("kg", "Kongo"),
    LangOption("kj", "Kuanyama"),
    LangOption("ku", "Kurdish"),
    LangOption("la", "Latin"),
    LangOption("li", "Limburgish"),
    LangOption("ln", "Lingala"),
    LangOption("lu", "Luba-Katanga"),
    LangOption("mg", "Malagasy"),
    LangOption("gv", "Manx"),
    LangOption("mi", "Māori"),
    LangOption("mh", "Marshallese"),
    LangOption("na", "Nauru"),
    LangOption("nv", "Navajo"),
    LangOption("ng", "Ndonga"),
    LangOption("nd", "North Ndebele"),
    LangOption("se", "Northern Sami"),
    LangOption("nb", "Norwegian Bokmål"),
    LangOption("nn", "Norwegian Nynorsk"),
    LangOption("ny", "Nyanja"),
    LangOption("oc", "Occitan"),
    LangOption("or", "Odia"),
    LangOption("oj", "Ojibwa"),
    LangOption("om", "Oromo"),
    LangOption("os", "Ossetic"),
    LangOption("pi", "Pali"),
    LangOption("qu", "Quechua"),
    LangOption("rm", "Romansh"),
    LangOption("rn", "Rundi"),
    LangOption("sm", "Samoan"),
    LangOption("sg", "Sango"),
    LangOption("sa", "Sanskrit"),
    LangOption("sc", "Sardinian"),
    LangOption("gd", "Scottish Gaelic"),
    LangOption("sn", "Shona"),
    LangOption("ii", "Sichuan Yi"),
    LangOption("sd", "Sindhi"),
    LangOption("so", "Somali"),
    LangOption("nr", "South Ndebele"),
    LangOption("st", "Southern Sotho"),
    LangOption("su", "Sundanese"),
    LangOption("ss", "Swati"),
    LangOption("ty", "Tahitian"),
    LangOption("tt", "Tatar"),
    LangOption("bo", "Tibetan"),
    LangOption("ti", "Tigrinya"),
    LangOption("to", "Tongan"),
    LangOption("ts", "Tsonga"),
    LangOption("tn", "Tswana"),
    LangOption("tk", "Turkmen"),
    LangOption("ug", "Uyghur"),
    LangOption("ve", "Venda"),
    LangOption("vo", "Volapük"),
    LangOption("wa", "Walloon"),
    LangOption("fy", "Western Frisian"),
    LangOption("wo", "Wolof"),
    LangOption("xh", "Xhosa"),
    LangOption("yi", "Yiddish"),
    LangOption("za", "Zhuang"),
    LangOption("zu", "Zulu"),
)

fun langLabel(code: String): String =
    TCALL_LANGUAGES.find { it.code == code }?.label ?: code.uppercase()
