package uz.tcall.socket

object SocketEvents {
    const val REGISTER_USER = "register-user"
    const val JOIN_ROOM = "join-room"
    const val LEAVE_ROOM = "leave-room"
    const val OFFER = "offer"
    const val ANSWER = "answer"
    const val ICE_CANDIDATE = "ice-candidate"
    const val REQUEST_REOFFER = "request-reoffer"
    const val CALL_ENDED = "call-ended"
    const val CALL_CANCEL = "call-cancel"
    const val CALL_ACCEPT = "call-accept"
    const val CALL_REJECT = "call-reject"
    const val CHAT_TYPING = "chat-typing"
    const val CHAT_TYPING_STOP = "chat-typing-stop"

    const val INCOMING_CALL = "incoming-call"
    const val CALL_ACCEPTED = "call-accepted"
    const val CALL_REJECTED = "call-rejected"
    const val CALL_CANCELLED = "call-cancelled"
    const val ROOM_USERS = "room-users"
    const val ROOM_FULL = "room-full"
    const val ROOM_ERROR = "room-error"
    const val CHAT_MESSAGE = "chat-message"
    const val CHAT_MESSAGE_DELETED = "chat-message-deleted"
    const val CHAT_MESSAGE_EDITED = "chat-message-edited"
    const val CHAT_READ = "chat-read"
    const val TRANSLATION = "translation"
}
