-keepclassmembers class uz.tcall.bridge.WebAppBridge { *; }
-keep class uz.tcall.bridge.** { *; }
-keep class uz.tcall.session.** { *; }
-keep class com.google.firebase.** { *; }
-dontwarn com.google.firebase.**
