package uz.tcall.ui.strings

data class TcallUiStrings(
    val messages: String,
    val friends: String,
    val keypad: String,
    val room: String,
    val interpreter: String,
    val yourNumber: String,
    val newChat: String,
    val newGroup: String,
    val search: String,
    val searchMessages: String,
    val searchById: String,
    val dialNumber: String,
    val recents: String,
    val all: String,
    val missed: String,
    val incoming: String,
    val outgoing: String,
    val nameOrNumber: String,
    val createRoom: String,
    val startCall: String,
    val join: String,
    val roomCode: String,
    val enableMic: String,
    val iSpeak: String,
    val theySpeak: String,
    val hold: String,
    val numbers: String,
    val settings: String,
    val logout: String,
    val support: String,
    val blacklist: String,
    val call: String,
    val buy: String,
    val catalog: String,
    val dialCustom: String,
    val yourNum: String,
    val premiumNumber: String,
    val unknown: String,
    val roomTitle: String,
    val roomSubtitle: String,
    val joinSubtitle: String,
    val aiTranslation: String,
    val interpreterTitle: String,
    val interpreterSubtitle: String,
    val holdHint: String,
    val supportSubtitle: String,
    val supportPlaceholder: String,
    val supportHint: String,
    val numbersSubtitle: String,
    val removeFriend: String,
    val noCalls: String,
    val friendsSection: String,
    val startChat: String,
    val createGroup: String,
    val groupName: String,
    val groupMembersHint: String,
    val roomReady: String,
    val inRoom: String,
    val roomOwner: String,
    val waitingGuest: String,
    val copyLink: String,
    val copied: String,
    val shareLink: String,
    val enterRoom: String,
    val createNewRoom: String,
    val block: String,
    val unblock: String,
    val blacklistDesc: String,
    val blacklistEmpty: String,
    val message: String,
    val viewOriginal: String,
    val chatTranslated: String,
    val close: String,
    val save: String,
    val myData: String,
    val myDataHint: String,
    val profileDetails: String,
    val profileDetailsHint: String,
    val preferences: String,
    val preferencesHint: String,
    val notifications: String,
    val notificationsHint: String,
    val changePassword: String,
    val changePasswordHint: String,
    val yourNumberLabel: String,
)

fun uiStrings(language: String): TcallUiStrings {
    val ru = language.startsWith("ru")
    val en = language.startsWith("en")
    return when {
        ru -> TcallUiStrings(
            messages = "Сообщения", friends = "Друзья", keypad = "Набор", room = "Комната",
            interpreter = "Переводчик", yourNumber = "ВАШ НОМЕР", newChat = "Новый чат",
            newGroup = "Группа", search = "Искать", searchMessages = "Поиск сообщений",
            searchById = "123456789", dialNumber = "Наберите номер",
            recents = "Недавние", all = "Все", missed = "Пропущенные", incoming = "Входящие",
            outgoing = "Исходящие", nameOrNumber = "Имя или номер", createRoom = "Создать комнату",
            startCall = "Начать звонок", join = "Присоединиться", roomCode = "КОД КОМНАТЫ",
            enableMic = "Включить микрофон", iSpeak = "Я говорю", theySpeak = "Он/она говорит",
            hold = "Удерживайте", numbers = "Номера", settings = "Настройки", logout = "Выход",
            support = "Поддержка", blacklist = "Чёрный список", call = "Звонок", buy = "Купить",
            catalog = "Каталог", dialCustom = "Набрать номер", yourNum = "Ваш номер",
            premiumNumber = "Премиум номер", unknown = "Неизвестно",
            roomTitle = "Комната для звонка",
            roomSubtitle = "Отправьте ссылку — AI переводит в реальном времени",
            joinSubtitle = "Введите код комнаты или перейдите по ссылке",
            aiTranslation = "AI tarjima",
            interpreterTitle = "Переводчик в реальном времени",
            interpreterSubtitle = "Держите телефон между вами — речь переводится и озвучивается",
            holdHint = "Удерживайте кнопку — отпустите для перевода и озвучки",
            supportSubtitle = "Свяжитесь с админом — пишите на любом языке",
            supportPlaceholder = "Напишите сообщение...",
            supportHint = "Вы пишете на своём языке, админ видит перевод, а ответ переводится на ваш язык.",
            numbersSubtitle = "Выберите номер — ID изменится после подтверждения админом",
            removeFriend = "Удалить", noCalls = "Звонков пока нет", friendsSection = "Друзья",
            startChat = "Начать чат", createGroup = "Создать группу",
            groupName = "Название группы",
            groupMembersHint = "Номера участников (через запятую или с новой строки)",
            roomReady = "Комната готова — отправьте ссылку", inRoom = "В КОМНАТЕ",
            roomOwner = "Владелец", waitingGuest = "Ожидание собеседника...",
            copyLink = "Копировать", copied = "Скопировано", shareLink = "Поделиться",
            enterRoom = "Войти в комнату", createNewRoom = "Создать новую комнату",
            block = "Заблокировать", unblock = "Разблокировать",
            blacklistDesc = "Заблокированные не могут звонить и писать вам",
            blacklistEmpty = "Чёрный список пуст",
            message = "Сообщение", viewOriginal = "Показать оригинал", chatTranslated = "Перевод",
            close = "Закрыть", save = "Сохранить",
            myData = "Мои данные", myDataHint = "Профиль, аватар и личная информация",
            profileDetails = "Детали профиля",
            profileDetailsHint = "Возраст, адрес, работа и образование",
            preferences = "Параметры", preferencesHint = "Язык, перевод и статус",
            notifications = "Уведомления",
            notificationsHint = "Управление push и разрешениями",
            changePassword = "Сменить пароль",
            changePasswordHint = "Обновите пароль для безопасности аккаунта",
            yourNumberLabel = "Ваш номер",
        )
        en -> TcallUiStrings(
            messages = "Messages", friends = "Friends", keypad = "Keypad", room = "Room",
            interpreter = "Interpreter", yourNumber = "YOUR NUMBER", newChat = "New chat",
            newGroup = "Group", search = "Search", searchMessages = "Search messages",
            searchById = "123456789", dialNumber = "Dial a number",
            recents = "Recents", all = "All", missed = "Missed", incoming = "Incoming",
            outgoing = "Outgoing", nameOrNumber = "Name or number", createRoom = "Create room",
            startCall = "Start call", join = "Join", roomCode = "ROOM CODE",
            enableMic = "Enable microphone", iSpeak = "I speak", theySpeak = "They speak",
            hold = "Hold", numbers = "Numbers", settings = "Settings", logout = "Log out",
            support = "Support", blacklist = "Blacklist", call = "Call", buy = "Buy",
            catalog = "Catalog", dialCustom = "Dial number", yourNum = "Your number",
            premiumNumber = "Premium number", unknown = "Unknown",
            roomTitle = "Room for a call",
            roomSubtitle = "Send a link — AI translates in real time",
            joinSubtitle = "Enter room code or open the link",
            aiTranslation = "AI translation",
            interpreterTitle = "Real-time interpreter",
            interpreterSubtitle = "Hold the phone between you — speech is translated and voiced",
            holdHint = "Hold the button — release to translate and speak",
            supportSubtitle = "Contact admin — write in any language",
            supportPlaceholder = "Write a message...",
            supportHint = "You write in your language; admin sees translation and replies are translated back.",
            numbersSubtitle = "Choose a number — ID changes after admin approval",
            removeFriend = "Remove", noCalls = "No calls yet", friendsSection = "Friends",
            startChat = "Start chat", createGroup = "Create group",
            groupName = "Group name",
            groupMembersHint = "Member numbers (comma or new line)",
            roomReady = "Room ready — send the link", inRoom = "IN ROOM",
            roomOwner = "Owner", waitingGuest = "Waiting for guest...",
            copyLink = "Copy", copied = "Copied", shareLink = "Share",
            enterRoom = "Enter room", createNewRoom = "Create new room",
            block = "Block", unblock = "Unblock",
            blacklistDesc = "Blocked users cannot call or message you",
            blacklistEmpty = "Blacklist is empty",
            message = "Message", viewOriginal = "Show original", chatTranslated = "Translation",
            close = "Close", save = "Save",
            myData = "My data", myDataHint = "Profile, avatar and personal info",
            profileDetails = "Profile details",
            profileDetailsHint = "Age, address, work and education",
            preferences = "Preferences", preferencesHint = "Language, translation and status",
            notifications = "Notifications",
            notificationsHint = "Manage push and permissions",
            changePassword = "Change password",
            changePasswordHint = "Update password for account security",
            yourNumberLabel = "Your number",
        )
        else -> TcallUiStrings(
            messages = "Xabarlar", friends = "Do'stlar", keypad = "Terish", room = "Xona",
            interpreter = "Tarjimon", yourNumber = "SIZNING RAQAMINGIZ", newChat = "Yangi chat",
            newGroup = "Guruh", search = "Qidirish", searchMessages = "Xabarlarni qidirish",
            searchById = "123456789", dialNumber = "Raqam tering",
            recents = "So'nggi", all = "Hammasi", missed = "O'tkazib yuborilgan",
            incoming = "Kiruvchi", outgoing = "Chiquvchi", nameOrNumber = "Ism yoki raqam",
            createRoom = "Xona yaratish", startCall = "Qo'ng'iroqni boshlash", join = "Qo'shilish",
            roomCode = "XONA KODI", enableMic = "Mikrofonni yoqish", iSpeak = "Men gapiraman",
            theySpeak = "U gapiradi", hold = "Ushlab turing", numbers = "Raqamlar",
            settings = "Sozlamalar", logout = "Chiqish", support = "Yordam",
            blacklist = "Qora ro'yxat", call = "Qo'ng'iroq", buy = "Sotib olish",
            catalog = "Katalog", dialCustom = "Raqam terish", yourNum = "Sizning raqamingiz",
            premiumNumber = "Premium raqam", unknown = "Noma'lum",
            roomTitle = "Qo'ng'iroq xonasi",
            roomSubtitle = "Havola yuboring — AI real vaqtda tarjima qiladi",
            joinSubtitle = "Xona kodini kiriting yoki havoladan o'ting",
            aiTranslation = "AI tarjima",
            interpreterTitle = "Jonli tarjimon",
            interpreterSubtitle = "Telefonni o'rtangizga qo'ying — nutq tarjima va ovozlanadi",
            holdHint = "Tugmani ushlab turing — tarjima va ovoz uchun qo'yib yuboring",
            supportSubtitle = "Admin bilan bog'laning — istalgan tilda yozing",
            supportPlaceholder = "Xabaringizni yozing...",
            supportHint = "Siz o'z tilingizda yozasiz, admin tarjimasini ko'radi va javobi sizning tilingizga tarjima bo'ladi.",
            numbersSubtitle = "Raqam tanlang — admin tasdiqlagach ID o'zgaradi",
            removeFriend = "O'chirish", noCalls = "Hali qo'ng'iroqlar yo'q", friendsSection = "Do'stlar",
            startChat = "Chatni boshlash", createGroup = "Guruh yaratish",
            groupName = "Guruh nomi",
            groupMembersHint = "A'zo raqamlari (vergul yoki yangi qator)",
            roomReady = "Xona tayyor — havola yuboring", inRoom = "XONADA",
            roomOwner = "Egasi", waitingGuest = "Suhbatdosh kutilmoqda...",
            copyLink = "Nusxa olish", copied = "Nusxa olindi", shareLink = "Ulashish",
            enterRoom = "Xonaga kirish", createNewRoom = "Yangi xona yaratish",
            block = "Bloklash", unblock = "Blokdan chiqarish",
            blacklistDesc = "Bloklanganlar sizga qo'ng'iroq va xabar yubora olmaydi",
            blacklistEmpty = "Qora ro'yxat bo'sh",
            message = "Xabar", viewOriginal = "Aslini ko'rsatish", chatTranslated = "Tarjima",
            close = "Yopish", save = "Saqlash",
            myData = "Mening ma'lumotlarim", myDataHint = "Profil, avatar va shaxsiy ma'lumot",
            profileDetails = "Profil tafsilotlari",
            profileDetailsHint = "Yosh, manzil, ish va ta'lim",
            preferences = "Parametrlar", preferencesHint = "Til, tarjima va holat",
            notifications = "Bildirishnomalar",
            notificationsHint = "Push va ruxsatlarni boshqarish",
            changePassword = "Parolni o'zgartirish",
            changePasswordHint = "Hisob xavfsizligi uchun yangi parol",
            yourNumberLabel = "Sizning raqamingiz",
        )
    }
}

fun tabLabel(tab: uz.tcall.ui.components.PhoneTab, ui: TcallUiStrings): String = when (tab) {
    uz.tcall.ui.components.PhoneTab.MESSAGES -> ui.messages
    uz.tcall.ui.components.PhoneTab.FRIENDS -> ui.friends
    uz.tcall.ui.components.PhoneTab.KEYPAD -> ui.keypad
    uz.tcall.ui.components.PhoneTab.ROOM -> ui.room
    uz.tcall.ui.components.PhoneTab.INTERPRETER -> ui.interpreter
}
